export const rebuildMission = {
  productName: "Answered.City",
  referenceProduct: "sawcity-lite",
  customerTargetLow: 1000,
  customerTargetHigh: 2000,
  deadline: "2026-12-31",
  monthsRemaining: 8,
  price: "$39/mo",
  trial: "14-day free trial, no credit card required",
  readOnlyReference: "sawcity-lite stays read-only; 4H is the rebuild surface.",
};

export const imageDriver = {
  provider: "ChatGPT Pro",
  model: "chatgpt-image-latest",
  role: "Main creative driver for ad images, UGC frames, demo visuals, and remix variants.",
  operatingRule:
    "Generate real trade-context visuals here with the Pro plan, then store the finished asset in 4H. No generic SaaS art, no stock-like filler.",
};

export const beachheadTrades = [
  {
    domain: "pipe.city",
    trade: "Plumbing",
    reason: "High emergency intent, clear missed-call pain, and strong value story for 24/7 answering.",
    firstOffer: "Call pipe.city and hear the AI book a plumbing job.",
  },
  {
    domain: "duct.city",
    trade: "HVAC",
    reason: "Seasonal spikes make speed-to-lead obvious; emergency calls are expensive to miss.",
    firstOffer: "See how the AI handles after-hours no-cool and no-heat calls.",
  },
  {
    domain: "mow.city",
    trade: "Lawn care",
    reason: "Large owner-operator audience and strong creator ecosystem for low-cost proof.",
    firstOffer: "Turn missed mowing calls into scheduled estimates while crews are out.",
  },
  {
    domain: "pest.city",
    trade: "Pest control",
    reason: "Urgent homeowner anxiety maps well to fast response and pre-qualification.",
    firstOffer: "Let the AI answer, qualify the pest issue, and send the owner the job details.",
  },
  {
    domain: "coat.city",
    trade: "Painting",
    reason: "Estimate-heavy workflow where missed calls and slow follow-up quietly leak revenue.",
    firstOffer: "Capture paint estimate calls and send the owner a clean job summary.",
  },
] as const;

export const operatingLoops = [
  {
    name: "Creator Demo Loop",
    status: "active rebuild",
    owner: "Jarrad + Bob",
    metric: "Creators contacted, replies, signed posts, demo calls, paid customers",
    route: "/influencer",
    nextMove: "Recruit trade creators to call the live demo line on camera and show the job summary.",
  },
  {
    name: "Image Creative Loop",
    status: "new driver",
    owner: "Bob + ChatGPT Pro image generation",
    metric: "Concepts generated, approved assets, platform variants, winners",
    route: "/assets",
    nextMove: "Build chatgpt-image-latest prompts around specific missed-call scenes and demo proof frames.",
  },
  {
    name: "Demo Funnel Loop",
    status: "needs instrumentation",
    owner: "4H dashboard",
    metric: "Demo calls, signups, activations, trial starts, paid conversions",
    route: "/scorecard",
    nextMove: "Make every creator/ad asset point to a trackable domain, demo number, or trial path.",
  },
  {
    name: "Approval Loop",
    status: "guardrail",
    owner: "Jarrad",
    metric: "Ready assets approved or rejected within 24 hours",
    route: "/approval",
    nextMove: "Keep external launch gated until copy, image, and offer are approved.",
  },
] as const;

export const nextFourteenDays = [
  {
    day: "Day 1",
    target: "Rebuild the 4H home base",
    outcome: "Dashboard reflects the acquisition OS instead of the old ad-generation archive.",
  },
  {
    day: "Days 2-3",
    target: "Image prompt factory",
    outcome: "20 reusable chatgpt-image-latest prompt briefs across missed-call, demo-call, math, and owner-agent angles.",
  },
  {
    day: "Days 4-6",
    target: "Creator outreach sprint",
    outcome: "30 creator prospects qualified, 10 ready-to-send outreach drafts, first approvals queued.",
  },
  {
    day: "Days 7-10",
    target: "Demo proof assets",
    outcome: "First approved trade-specific demo clips and images ready for Meta, YouTube, and creator posts.",
  },
  {
    day: "Days 11-14",
    target: "Measurement gate",
    outcome: "Every launched asset has UTM, trade, creator, image variant, and demo-call attribution.",
  },
] as const;

export const customerMath = [
  {
    label: "Conservative path",
    value: "1,000",
    detail: "125 net new customers per month for 8 months.",
  },
  {
    label: "Ambitious path",
    value: "2,000",
    detail: "250 net new customers per month for 8 months.",
  },
  {
    label: "Price point",
    value: "$39",
    detail: "Trial-first offer: 14-day free trial, no credit card required.",
  },
  {
    label: "Current paid data",
    value: "0",
    detail: "4H has generated assets and prospects, but no live spend-to-customer signal yet.",
  },
] as const;

export const rebuildExecutionQueue = [
  {
    id: "Q-01",
    phase: "Phase 2",
    lane: "Creative",
    title: "Generate first beachhead image pack",
    route: "/assets",
    status: "ready",
    approval: "none",
    outcome: "20 prompt cards each have a generated image asset uploaded, still draft or review.",
    acceptance: "Every uploaded asset has trade, angle, model, prompt, variant ID, and preview image.",
  },
  {
    id: "Q-02",
    phase: "Phase 2",
    lane: "Creative",
    title: "Add creative review filters",
    route: "/assets",
    status: "complete",
    approval: "none",
    outcome: "Creative Lab can filter by status, trade, angle, and generation state.",
    acceptance: "Filters work without page reload and empty states are clear.",
  },
  {
    id: "Q-03",
    phase: "Phase 2",
    lane: "Creative",
    title: "Add variant replacement workflow",
    route: "/assets",
    status: "complete",
    approval: "none",
    outcome: "A generated image can spawn a v2/v3 prompt tied to the parent asset.",
    acceptance: "Parent/child lineage is visible and variant IDs remain stable.",
  },
  {
    id: "Q-04",
    phase: "Phase 2",
    lane: "Creative",
    title: "Create Claude Design handoff packet",
    route: "/assets",
    status: "ready",
    approval: "none",
    outcome: "A concise handoff file describes the Creative Lab UX, data model, and visual polish requests.",
    acceptance: "Packet is specific enough for a design pass without touching product strategy.",
  },
  {
    id: "Q-05",
    phase: "Phase 3",
    lane: "Creators",
    title: "Audit creator shortlist",
    route: "/influencer",
    status: "ready",
    approval: "none",
    outcome: "Creator list is split into keep, maybe, remove, and needs-research buckets.",
    acceptance: "Weak matches are not deleted; they are labeled or deprioritized.",
  },
  {
    id: "Q-06",
    phase: "Phase 3",
    lane: "Creators",
    title: "Upgrade creator scoring model",
    route: "/influencer",
    status: "ready",
    approval: "none",
    outcome: "Creator rows score owner audience, trade fit, trust, sponsor openness, and expected production value.",
    acceptance: "Scores render in the UI and are covered by tests.",
  },
  {
    id: "Q-07",
    phase: "Phase 3",
    lane: "Creators",
    title: "Draft creator outreach packets",
    route: "/influencer",
    status: "ready",
    approval: "review-required",
    outcome: "10 ready-to-review outreach drafts tied to a trade, demo offer, and tracking link.",
    acceptance: "No outreach is sent; drafts are approval-gated.",
  },
  {
    id: "Q-08",
    phase: "Phase 3",
    lane: "Creators",
    title: "Add creator UTM builder",
    route: "/influencer",
    status: "ready",
    approval: "none",
    outcome: "Each creator can receive a deterministic UTM/referral URL.",
    acceptance: "URL includes creator, trade, platform, campaign, and content IDs.",
  },
  {
    id: "Q-09",
    phase: "Phase 3",
    lane: "Creators",
    title: "Build content brief templates",
    route: "/templates",
    status: "ready",
    approval: "none",
    outcome: "Demo-call video, founder assist, and screenshot-proof templates exist.",
    acceptance: "Templates include hook, shot list, CTA, offer, and tracking guidance.",
  },
  {
    id: "Q-10",
    phase: "Phase 4",
    lane: "Landing",
    title: "Inventory read-only product routes",
    route: "/gtm",
    status: "ready",
    approval: "none",
    outcome: "4H has a registry of live trade domains, landing paths, and demo phone assumptions.",
    acceptance: "sawcity-lite is read only; findings are copied into 4H docs/data only.",
  },
  {
    id: "Q-11",
    phase: "Phase 4",
    lane: "Landing",
    title: "Create launch URL builder",
    route: "/launch",
    status: "ready",
    approval: "none",
    outcome: "Launch URLs can be generated from trade, platform, creator, asset, and angle.",
    acceptance: "UTM format matches AGENTS.md and tests cover key permutations.",
  },
  {
    id: "Q-12",
    phase: "Phase 4",
    lane: "Landing",
    title: "Create message-match briefs",
    route: "/templates",
    status: "ready",
    approval: "none",
    outcome: "Each image/copy angle has a handoff brief for future sawcity-lite landing updates.",
    acceptance: "Briefs do not edit sawcity-lite and include $39/mo plus 14-day trial language.",
  },
  {
    id: "Q-13",
    phase: "Phase 4",
    lane: "Landing",
    title: "Add launch readiness validator",
    route: "/launch",
    status: "ready",
    approval: "none",
    outcome: "Assets fail preflight if missing domain, offer, UTM, creative approval, or Jarrad approval.",
    acceptance: "Validator returns actionable reasons and has unit tests.",
  },
  {
    id: "Q-14",
    phase: "Phase 5",
    lane: "Launch",
    title: "Archive historical ad library",
    route: "/ads",
    status: "ready",
    approval: "none",
    outcome: "Old ads are visibly archived so they cannot be mistaken for launch candidates.",
    acceptance: "No ad copy is deleted; statuses/labels preserve history.",
  },
  {
    id: "Q-15",
    phase: "Phase 5",
    lane: "Launch",
    title: "Build launch bundle model",
    route: "/launch",
    status: "ready",
    approval: "none",
    outcome: "A launch bundle connects trade, angle, image, copy, creator/proof, URL, budget, and approvals.",
    acceptance: "Bundles can be draft/review/approved but cannot launch externally.",
  },
  {
    id: "Q-16",
    phase: "Phase 5",
    lane: "Launch",
    title: "Add experiment budget allocation",
    route: "/budget",
    status: "ready",
    approval: "none",
    outcome: "Budget can be assigned by experiment, not only by channel.",
    acceptance: "No billing changes; this is planning state only.",
  },
  {
    id: "Q-17",
    phase: "Phase 5",
    lane: "Launch",
    title: "Create platform upload sheets",
    route: "/launch",
    status: "ready",
    approval: "review-required",
    outcome: "Meta, LinkedIn, YouTube, and Instagram CSV exports can be generated for approved bundles.",
    acceptance: "Exporting is local/download-only and does not upload to ad accounts.",
  },
  {
    id: "Q-18",
    phase: "Phase 6",
    lane: "Learning",
    title: "Upgrade weekly report",
    route: "/scorecard",
    status: "ready",
    approval: "none",
    outcome: "Weekly report ranks trades, creators, images, and angles by funnel performance.",
    acceptance: "Zero-data states are honest and do not fabricate recommendations.",
  },
  {
    id: "Q-19",
    phase: "Phase 6",
    lane: "Learning",
    title: "Add keep/kill/iterate decisions",
    route: "/scorecard",
    status: "ready",
    approval: "none",
    outcome: "Experiments can be marked keep, kill, iterate, or scale with notes.",
    acceptance: "Decision history is visible and reversible.",
  },
  {
    id: "Q-20",
    phase: "Phase 6",
    lane: "Learning",
    title: "Add customer pace forecast",
    route: "/scorecard",
    status: "ready",
    approval: "none",
    outcome: "Dashboard shows monthly customer target, actual pace, and gap to 1,000/2,000.",
    acceptance: "Uses real paid customer data when available and clear placeholders otherwise.",
  },
  {
    id: "Q-21",
    phase: "Phase 6",
    lane: "Research",
    title: "Validate Meta Ad Library access",
    route: "/templates",
    status: "ready",
    approval: "none",
    outcome: "Competitive research path is validated before relying on automated ad-library collection.",
    acceptance: "Report distinguishes official API limits from assumptions.",
  },
  {
    id: "Q-22",
    phase: "Phase 6",
    lane: "Research",
    title: "Create competitor research report template",
    route: "/templates",
    status: "ready",
    approval: "none",
    outcome: "A repeatable report format captures offers, hooks, visuals, platforms, and evidence quality.",
    acceptance: "Template avoids scraped-data overconfidence and includes citation fields.",
  },
  {
    id: "Q-23",
    phase: "Governance",
    lane: "Safety",
    title: "Add approval audit log",
    route: "/approval",
    status: "ready",
    approval: "none",
    outcome: "Major approval actions have who/when/what/why metadata.",
    acceptance: "Audit log covers creative, outreach, launch bundle, and export approvals.",
  },
  {
    id: "Q-24",
    phase: "Governance",
    lane: "Safety",
    title: "Add external-action stop screen",
    route: "/launch",
    status: "ready",
    approval: "none",
    outcome: "Any action that could launch, send, upload, or spend clearly stops for Jarrad.",
    acceptance: "UI copy explains the exact approval needed and no external API calls happen.",
  },
] as const;
