// Shared project state — imported directly by both the API route and the GTM page.
// No HTTP self-fetch needed. Update this file to refresh all GTM board data.

export function getProjectState() {
  return {
    lastUpdated: '2026-02-28',
    version: '3.0.0',

    product: {
      name: 'Saw.City LITE',
      headline: 'AI phone receptionist + owner agent + job management for trades',
      url: 'https://sawcity-lite.vercel.app',
      status: 'production',
      summary: 'One codebase, 20 .city domains. AI answers the phone, texts the owner, and lets them manage jobs by voice. $79/mo, no demo, self-serve.',

      readiness: [
        { label: 'AI Receptionist (20 trades)', status: 'done', note: 'Answers calls, qualifies leads, creates jobs, texts owner' },
        { label: 'Owner Agent (voice + text)', status: 'done', note: '23 tools — scheduling, estimates, briefings, email, notes' },
        { label: 'Mobile PWA', status: 'done', note: 'Jobs, customers, calls, photos, billing. Works offline.' },
        { label: '20 Trade Domains Live', status: 'done', note: 'saw.city, rinse.city, pipe.city, lockout.city, mow.city + 15 more' },
        { label: 'Onboarding Interview', status: 'done', note: 'Voice-powered business config extraction on first login' },
        { label: 'Email Integration (Resend)', status: 'done', note: '20 .city domains verified, branded HTML templates' },
        { label: 'TCPA / SMS Compliance', status: 'done', note: 'Opt-out handling, consent tracking, privacy/terms pages live' },
        { label: 'Stripe Billing ($79/mo)', status: 'done', note: 'Single tier, no feature gating. Trial → paid flow.' },
        { label: 'Admin Panel', status: 'done', note: '10 pages — tenants, trades, logs, health, demo funnel, changelog' },
        { label: 'A2P 10DLC Campaign', status: 'in-review', note: 'TCR campaign under review (~2-3 weeks). SMS unblocked after approval.' },
        { label: 'Per-trade tool customization', status: 'pending', note: 'Different tool sets per trade (e.g. locksmith vs concrete cutter)' },
        { label: 'Job map view', status: 'pending', note: 'Plot active jobs on Google Map — post-launch P1' },
        { label: 'Route optimization', status: 'pending', note: 'Reorder daily jobs by optimal driving route — P2' },
      ],

      metrics: {
        backend_tests: 467,
        frontend_tests: 343,
        total_tests: 810,
        api_endpoints: 71,
        trade_domains: 20,
        monthly_price: 79,
        gross_margin_pct: '77–86%',
      },
    },

    campaign: {
      name: 'Project 4H',
      mission: '2,000 USERS — this is the number. Not 1,000. Not "customers." 2,000 users on Saw.City LITE.',
      target_users: 2000,
      budget_total: 20000,
      channels: ['LinkedIn', 'YouTube', 'Facebook', 'Instagram'],
      status: 'pre-launch',
      dashboard: 'https://pumpcans.com',
      // Campaign Phase 1 trades (ads already built for these 4)
      tier1_trades: [
        { domain: 'pipe.city', slug: 'plumbing', appName: 'Pipe.City', trade: 'Plumbing' },
        { domain: 'mow.city', slug: 'lawn-care', appName: 'Mow.City', trade: 'Lawn Care' },
        { domain: 'coat.city', slug: 'painting', appName: 'Coat.City', trade: 'Painting' },
        { domain: 'duct.city', slug: 'hvac', appName: 'Duct.City', trade: 'HVAC' },
        { domain: 'pest.city', slug: 'pest-control', appName: 'Pest.City', trade: 'Pest Control' },
      ],
      // TAM-ranked tiers (source: Feb 2026 trade research). Tier = opportunity rank, not campaign phase.
      // Campaign Phase 1 ads were built for: saw / rinse / mow / rooter (brand familiarity; not TAM-driven)
      all_trades: [
        // TIER 1 — Massive TAM + high operator count + strong product fit (LIVE)
        { domain: 'pipe.city',     slug: 'plumbing',         appName: 'Pipe.City',    tier: 1, tam: '$191B', businesses: '130K', note: 'Emergency 24/7, huge solo operator base', status: 'live' },
        { domain: 'mow.city',      slug: 'lawn-care',        appName: 'Mow.City',     tier: 1, tam: '$60B',  businesses: '500K+', note: '55% solo operators, largest addressable pool', status: 'live' },
        { domain: 'coat.city',     slug: 'painting',         appName: 'Coat.City',    tier: 1, tam: '$28B',  businesses: '220K', note: 'Highest operator count of any trade', status: 'live' },
        { domain: 'duct.city',     slug: 'hvac',             appName: 'Duct.City',    tier: 1, tam: '$30B',  businesses: '105K', note: 'Emergency demand, high job value', status: 'live' },
        { domain: 'pest.city',     slug: 'pest-control',     appName: 'Pest.City',    tier: 1, tam: '$26B',  businesses: '33K',  note: 'Recurring revenue model, scheduled visits', status: 'live' },
        // TIER 1 — Upcoming
        { domain: 'electricians.city', slug: 'electrical',    appName: 'Electricians.City', tier: 1, tam: '$220B', businesses: '100K+', note: 'Primary electrical domain. Emergency calls, owner-operators, Tier 1 alongside pipe+duct', status: 'upcoming' },
        { domain: 'roofrepair.city',  slug: 'roofing',       appName: 'Roofrepair.City',  tier: 1, tam: '$56B',  businesses: '100K+', note: 'Primary roofing domain. Storm emergency, insurance jobs, high value. roof.city was $10K+ premium', status: 'upcoming' },
        { domain: 'crimp.city',    slug: 'electrical-alt',   appName: 'Crimp.City',   tier: 1, tam: 'see electricians.city', businesses: '', note: 'Forwards to Electricians.City', status: 'forward', forwardsTo: 'electricians.city' },
        { domain: 'eave.city',     slug: 'roofing-alt',      appName: 'Eave.City',    tier: 1, tam: 'see roofrepair.city', businesses: '', note: 'Forwards to Roofrepair.City', status: 'forward', forwardsTo: 'roofrepair.city' },
        { domain: 'excavation.city', slug: 'excavation',     appName: 'Excavation.City', tier: 1, tam: '$200B', businesses: '235K', note: "Kippen's own trade. Site prep, utility trenching, earthwork", status: 'upcoming' },
        { domain: 'disaster.city', slug: 'disaster-restoration', appName: 'Disaster.City', tier: 1, tam: '$210B', businesses: '30K+', note: 'Fire/flood/storm restoration. Insurance-driven, 24/7 emergency', status: 'upcoming' },
        // TIER 2 — Large TAM or high urgency fit (LIVE)
        { domain: 'prune.city',    slug: 'tree-service',     appName: 'Prune.City',   tier: 2, tam: '$39.5B', businesses: '50K+', note: 'Storm emergency + seasonal surge', status: 'live' },
        { domain: 'brake.city',    slug: 'auto-repair',      appName: 'Brake.City',   tier: 2, tam: '$90B',  businesses: '302K', note: 'Massive market; shop vs solo dynamics to test', status: 'live' },
        { domain: 'pave.city',     slug: 'paving',           appName: 'Pave.City',    tier: 2, tam: '$19B',  businesses: '30K+', note: 'Fragmented small operators, project-based', status: 'live' },
        { domain: 'plow.city',     slug: 'snow-removal',     appName: 'Plow.City',    tier: 2, tam: '$21B',  businesses: '106K', note: '80% sole proprietors; seasonal caveat', status: 'live' },
        { domain: 'lockout.city',  slug: 'locksmith',        appName: 'Lockout.City', tier: 2, tam: '$3B',   businesses: '25K',  note: 'Small market but highest urgency — missed call = job gone', status: 'live' },
        { domain: 'rooter.city',   slug: 'drain-cleaning',   appName: 'Rooter.City',  tier: 2, tam: '$8.1B', businesses: '7.7K', note: 'Emergency pull, high value jobs', status: 'live' },
        { domain: 'haul.city',     slug: 'hauling',          appName: 'Haul.City',    tier: 2, tam: '$6B',   businesses: '20K+', note: 'Junk removal segment; 30-40% missed call rate', status: 'live' },
        { domain: 'wreck.city',    slug: 'demolition',       appName: 'Wreck.City',   tier: 2, tam: '$22.7B', businesses: '45K+', note: 'Towing = 45K+ operators, high emergency demand', status: 'live' },
        // TIER 2 — Upcoming
        { domain: 'remodels.city', slug: 'remodeling',       appName: 'Remodels.City', tier: 2, tam: '$500B+', businesses: '800K+', note: 'Massive TAM but buyer skews larger — owner-operators first', status: 'upcoming' },
        { domain: 'gc.city',       slug: 'general-contracting', appName: 'GC.City',   tier: 2, tam: '$2T',   businesses: '800K+', note: 'Broadest trade category. May forward to remodels.city', status: 'upcoming' },
        { domain: 'bodyshop.city', slug: 'auto-body',        appName: 'Bodyshop.City', tier: 2, tam: '$57B', businesses: '35K',  note: 'Collision repair. High call volume, insurance estimates', status: 'upcoming' },
        { domain: 'drywall.city',  slug: 'drywall',          appName: 'Drywall.City', tier: 2, tam: '$50B',  businesses: '50K+', note: 'Crew-based, strong solo operator base', status: 'upcoming' },
        { domain: 'shrink.city',   slug: 'therapy',          appName: 'Shrink.City',  tier: 2, tam: '$50B',  businesses: '200K+', note: 'Solo practice owners — scheduling = missed revenue', status: 'upcoming' },
        { domain: 'sentry.city',   slug: 'security-alarms',  appName: 'Sentry.City',  tier: 2, tam: '$30B',  businesses: '15K',  note: 'Alarm install + monitoring. Recurring revenue model', status: 'upcoming' },
        { domain: 'renewables.city', slug: 'solar',          appName: 'Renewables.City', tier: 2, tam: '$30B', businesses: '15K', note: 'Solar install + maintenance, high job value', status: 'upcoming' },
        { domain: 'plank.city',    slug: 'flooring',         appName: 'Plank.City',   tier: 2, tam: '$30B',  businesses: '50K+', note: 'Hardwood, LVP, tile — high project volume', status: 'upcoming' },
        { domain: 'metalworks.city', slug: 'welding',        appName: 'Metalworks.City', tier: 2, tam: '$20B', businesses: '50K+', note: 'Mobile welders + fab shops, high missed call rate', status: 'upcoming' },
        { domain: 'refrigeration.city', slug: 'refrigeration', appName: 'Refrigeration.City', tier: 2, tam: '$20B', businesses: '20K', note: 'Emergency repair, commercial kitchens/walk-ins', status: 'upcoming' },
        { domain: 'housecleaning.city', slug: 'house-cleaning', appName: 'Housecleaning.City', tier: 2, tam: '$20B', businesses: '500K+', note: 'Massive operator base, recurring clients', status: 'upcoming' },
        { domain: 'insulation.city', slug: 'insulation',     appName: 'Insulation.City', tier: 2, tam: '$22B', businesses: '20K', note: 'Spray foam + batt, strong solo operator base', status: 'upcoming' },
        // TIER 3 — Niche, small market, or buyer mismatch (LIVE)
        { domain: 'grade.city',    slug: 'grading',          appName: 'Grade.City',   tier: 3, tam: '$203B', businesses: '235K', note: 'Giant market BUT mostly commercial/large operators — buyer mismatch', status: 'live' },
        { domain: 'chimney.city',  slug: 'chimney-sweep',    appName: 'Chimney.City', tier: 3, tam: '$170M', businesses: '8.2K', note: 'Small US market', status: 'live' },
        { domain: 'saw.city',      slug: 'concrete-cutting', appName: 'Saw.City',     tier: 3, tam: '$2.5B', businesses: '2K',   note: "Jarrad's home trade but smallest US market (~2K operators)", status: 'live' },
        { domain: 'rinse.city',    slug: 'pressure-washing', appName: 'Rinse.City',   tier: 3, tam: '$1.8B', businesses: '12K',  note: 'Small market, highly seasonal', status: 'live' },
        { domain: 'detail.city',   slug: 'auto-detailing',   appName: 'Detail.City',  tier: 3, tam: '$1.7B', businesses: '16.5K', note: 'Small US market, mobile detailers growing', status: 'live' },
        { domain: 'polish.city',   slug: 'floor-polishing',  appName: 'Polish.City',  tier: 3, tam: '$4B',   businesses: '20K',  note: 'Specialist niche, B2B-heavy', status: 'live' },
        { domain: 'wrench.city',   slug: 'mechanic',         appName: 'Wrench.City',  tier: 3, tam: 'sub-$90B', businesses: '620K mechanics', note: 'Individual mechanic focus; different buyer than shop owner', status: 'live' },
        // TIER 3 — Upcoming
        { domain: 'siding.city',   slug: 'siding',           appName: 'Siding.City',  tier: 3, tam: '$15B',  businesses: '25K',  note: 'Project-based, seasonal, crew-driven', status: 'upcoming' },
        { domain: 'rolloff.city',  slug: 'dumpster',         appName: 'Rolloff.City', tier: 3, tam: '$15B',  businesses: '5K',   note: 'Dispatch-heavy, high call volume, time-sensitive', status: 'upcoming' },
        { domain: 'poolservice.city', slug: 'pool-service',  appName: 'Poolservice.City', tier: 3, tam: '$13B', businesses: '50K', note: 'Recurring service routes, scheduling critical', status: 'upcoming' },
        { domain: 'hitch.city',    slug: 'towing',           appName: 'Hitch.City',   tier: 3, tam: '$11B',  businesses: '45K',  note: 'Towing companies. 24/7 emergency, high missed call rate', status: 'upcoming' },
        { domain: 'appraisals.city', slug: 'appraisals',     appName: 'Appraisals.City', tier: 3, tam: '$12B', businesses: '20K', note: 'Solo appraisers, appointment-driven', status: 'upcoming' },
        { domain: 'carpetcleaning.city', slug: 'carpet-cleaning', appName: 'Carpetcleaning.City', tier: 3, tam: '$6B', businesses: '30K', note: 'Project-based, scheduling-driven', status: 'upcoming' },
        { domain: 'mold.city',     slug: 'mold-remediation', appName: 'Mold.City',    tier: 3, tam: '$10B',  businesses: '10K',  note: 'Emergency/inspection-driven, high job value', status: 'upcoming' },
        { domain: 'fireprotection.city', slug: 'fire-protection', appName: 'Fireprotection.City', tier: 3, tam: '$10B', businesses: '10K', note: 'Commercial inspection + install', status: 'upcoming' },
        { domain: 'groom.city',    slug: 'pet-grooming',     appName: 'Groom.City',   tier: 3, tam: '$10B',  businesses: '50K',  note: 'Appointment-based, high no-show rate, scheduling pain', status: 'upcoming' },
        { domain: 'pane.city',     slug: 'windows',          appName: 'Pane.City',    tier: 3, tam: '$8B',   businesses: '20K',  note: 'Project-based, measurement + install', status: 'upcoming' },
        { domain: 'alignment.city', slug: 'auto-alignment',  appName: 'Alignment.City', tier: 3, tam: '$8B', businesses: '30K',  note: 'Shop-based, walk-in + scheduled', status: 'upcoming' },
        { domain: 'finish.city',   slug: 'finish-carpentry', appName: 'Finish.City',  tier: 3, tam: '$8B',   businesses: '30K',  note: 'Interior trim, cabinet install', status: 'upcoming' },
        { domain: 'windshield.city', slug: 'windshield',     appName: 'Windshield.City', tier: 3, tam: '$4B', businesses: '15K', note: 'Insurance-driven, mobile repair', status: 'upcoming' },
        { domain: 'taxprep.city',  slug: 'tax-prep',         appName: 'Taxprep.City', tier: 3, tam: '$11B',  businesses: '100K+', note: 'Solo practitioners, seasonal surge', status: 'upcoming' },
        { domain: 'bookkeeper.city', slug: 'bookkeeping',    appName: 'Bookkeeper.City', tier: 3, tam: '$60B', businesses: '200K+', note: 'Solo bookkeepers, small firms', status: 'upcoming' },
        { domain: 'lawfirm.city',  slug: 'law',              appName: 'Lawfirm.City', tier: 3, tam: '$370B', businesses: '150K+', note: 'Solo practitioners + small firms — different buyer profile', status: 'upcoming' },
        { domain: 'inspection.city', slug: 'home-inspection', appName: 'Inspection.City', tier: 3, tam: '$5B', businesses: '25K', note: 'Appointment-driven, solo inspectors', status: 'upcoming' },
        { domain: 'septic.city',   slug: 'septic',           appName: 'Septic.City',  tier: 3, tam: '$5B',   businesses: '15K',  note: 'Emergency + scheduled pump-outs', status: 'upcoming' },
        { domain: 'nail.city',     slug: 'nail-salon',       appName: 'Nail.City',    tier: 3, tam: '$6B',   businesses: '50K',  note: 'Appointment-based, high scheduling pain', status: 'upcoming' },
        { domain: 'bartender.city', slug: 'bartending',      appName: 'Bartender.City', tier: 3, tam: '$25B', businesses: '50K+', note: 'Event-driven, booking-heavy', status: 'upcoming' },
        { domain: 'cater.city',    slug: 'catering',         appName: 'Cater.City',   tier: 3, tam: '$12B',  businesses: '50K+', note: 'Event-driven, booking-heavy', status: 'upcoming' },
        { domain: 'esthetician.city', slug: 'esthetics',     appName: 'Esthetician.City', tier: 3, tam: '$20B', businesses: '100K+', note: 'Solo practitioners, appointment-based', status: 'upcoming' },
        { domain: 'portrait.city', slug: 'photography',      appName: 'Portrait.City', tier: 3, tam: '$11B', businesses: '200K+', note: 'Solo/studio, booking-driven', status: 'upcoming' },
        { domain: 'privatechef.city', slug: 'private-chef',  appName: 'Privatechef.City', tier: 3, tam: '$5B', businesses: '20K', note: 'Booking-driven, high-end clients', status: 'upcoming' },
        { domain: 'grout.city',    slug: 'tile-grout',       appName: 'Grout.City',   tier: 3, tam: '$4B',   businesses: '15K',  note: 'Niche cleaning/install', status: 'upcoming' },
        { domain: 'stamped.city',  slug: 'stamped-concrete', appName: 'Stamped.City', tier: 3, tam: '$3B',   businesses: '10K',  note: 'Specialty concrete, seasonal', status: 'upcoming' },
        { domain: 'trowel.city',   slug: 'plastering',       appName: 'Trowel.City',  tier: 3, tam: '$5B',   businesses: '10K',  note: 'Specialty exterior/interior finish', status: 'upcoming' },
        { domain: 'directional.city', slug: 'directional-boring', appName: 'Directional.City', tier: 3, tam: '$5B', businesses: '5K', note: 'Specialized HDD drilling, project-based', status: 'upcoming' },
        { domain: 'hydrovac.city', slug: 'hydrovac',         appName: 'Hydrovac.City', tier: 3, tam: '$3B',  businesses: '2K',   note: 'Niche excavation, mostly commercial', status: 'upcoming' },
        { domain: 'locating.city', slug: 'utility-locating', appName: 'Locating.City', tier: 3, tam: '$2B',  businesses: '5K',   note: 'Solo locators, compliance-driven', status: 'upcoming' },
        // FORWARDING domains
        { domain: 'mechanic.city', slug: 'mechanic',         appName: 'Mechanic.City', tier: 3, tam: 'see wrench.city', businesses: '', note: 'Forwards to Wrench.City', status: 'forward', forwardsTo: 'wrench.city' },
        { domain: 'demolition.city', slug: 'demolition',     appName: 'Demolition.City', tier: 3, tam: 'see wreck.city', businesses: '', note: 'Forwards to Wreck.City', status: 'forward', forwardsTo: 'wreck.city' },
        { domain: 'bucket.city',   slug: 'excavation-alt',   appName: 'Bucket.City',  tier: 3, tam: 'see excavation.city', businesses: '', note: 'Forwards to Excavation.City', status: 'forward', forwardsTo: 'excavation.city' },
        { domain: 'esthetics.city', slug: 'esthetics-alt',   appName: 'Esthetics.City', tier: 3, tam: 'see esthetician.city', businesses: '', note: 'Forwards to Esthetician.City', status: 'forward', forwardsTo: 'esthetician.city' },
        { domain: 'answered.city', slug: 'answering-alt',    appName: 'Answered.City', tier: 3, tam: '', businesses: '', note: 'Potential forward to receptionist.city or platform feature', status: 'forward', forwardsTo: 'receptionist.city' },
        // PLATFORM domains (not trade communities)
        { domain: 'tradex.city',   slug: 'platform',         appName: 'Tradex.City',  tier: 0, tam: '', businesses: '', note: 'Future B2B marketplace between community members — not a trade', status: 'platform', forwardsTo: '' },
        { domain: 'vendor.city',   slug: 'platform',         appName: 'Vendor.City',  tier: 0, tam: '', businesses: '', note: 'Future verified supplier marketplace — not a trade community', status: 'platform', forwardsTo: '' },
        { domain: 'receptionist.city', slug: 'platform',     appName: 'Receptionist.City', tier: 0, tam: '', businesses: '', note: 'Potential standalone AI receptionist play or platform branding', status: 'platform', forwardsTo: '' },
      ],

      readiness: [
        { label: 'Strategy + Operating Pack', status: 'done', note: 'Kill/scale thresholds, UTM schema, weekly cadence defined' },
        { label: 'Ad Copy (27 ads approved)', status: 'done', note: '6 LinkedIn, 7 YouTube, 4 Facebook, 4 Instagram, 6 retargeting — all approved' },
        { label: '16 Ad Creatives (Tier 1)', status: 'done', note: '4 trades × 4 platforms — Nano Banana Pro generated, at pumpcans.com/creatives' },
        { label: 'Creative Briefs + Prompts', status: 'done', note: 'Every creative has full prompt/model/asset brief logged for iteration' },
        { label: 'Lifecycle Messaging (Day 0/1/3)', status: 'done', note: 'Email + SMS sequences approved' },
        { label: 'Landing Page Blocks', status: 'done', note: '/li /yt /fb /ig variants + section blocks approved' },
        { label: 'Upload-ready CSVs', status: 'done', note: 'CAMPAIGN-UPLOAD-SHEET-v2.csv — 27 rows, all platforms' },
        { label: 'Platform Setup Guides', status: 'done', note: 'LinkedIn, Meta, YouTube step-by-step upload guides ready' },
        { label: 'Ad approval queue', status: 'in-progress', note: '81 trade-specific copy variants pending review at pumpcans.com/approval' },
        { label: 'Conversion tracking (4H DB)', status: 'done', note: 'marketing_events table live in 4H Supabase — UTM attribution ready' },
        { label: 'Ad account + pixel setup', status: 'pending', note: 'LinkedIn Campaign Manager, Meta Ads, Google/YouTube Ads — Jarrad initiates' },
        { label: 'A2P SMS approval', status: 'blocked', note: 'Lifecycle SMS blocked until TCR campaign approved (~2-3 weeks)' },
      ],
    },

    actions: [
      {
        priority: 1,
        label: 'Review ad copy at pumpcans.com/approval',
        effort: '10 min',
        owner: 'Jarrad',
        detail: '81 trade-specific copy variants (Rinse/Mow/Rooter) pending approve/revise/reject. Nothing uploads without your sign-off.',
        link: 'https://pumpcans.com/approval',
      },
      {
        priority: 2,
        label: 'Set up ad accounts + pixels',
        effort: '2–3 hrs',
        owner: 'Jarrad + Bob',
        detail: 'LinkedIn Campaign Manager, Meta Ads Manager, Google Ads. Bob walks through each setup guide step-by-step.',
        link: null,
      },
      {
        priority: 3,
        label: 'Upload creatives + launch campaigns',
        effort: '1–2 hrs',
        owner: 'Bob',
        detail: '16 creatives ready at pumpcans.com/creatives. Bob packages per-platform with UTMs + targeting specs once accounts are live.',
        link: 'https://pumpcans.com/creatives',
      },
      {
        priority: 4,
        label: 'A2P 10DLC approval',
        effort: 'Waiting',
        owner: 'TCR (auto)',
        detail: 'SMS lifecycle blocked until approved. Campaign registered 2026-02-22. ETA: ~2-3 weeks from TCR.',
        link: null,
      },
    ],

    keyLinks: [
      { label: 'Ad Creatives', url: 'https://pumpcans.com/creatives' },
      { label: 'Approval Queue', url: 'https://pumpcans.com/approval' },
      { label: 'Campaign Dashboard', url: 'https://pumpcans.com' },
      { label: 'GTM Board', url: 'https://pumpcans.com/gtm' },
      { label: 'Saw.City LITE (prod)', url: 'https://sawcity-lite.vercel.app' },
      { label: 'Supabase DB (4H)', url: 'https://supabase.com/dashboard/project/vzawlfitqnjhypnkguas' },
    ],
  };
}

export type ProjectState = ReturnType<typeof getProjectState>;
