#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const dataDir = path.join(__dirname, '..', 'data');
const outDir = path.join(__dirname, '..', 'supabase', 'migrations');

const ads = JSON.parse(fs.readFileSync(path.join(dataDir, 'ads.json')));
const lifecycle = JSON.parse(fs.readFileSync(path.join(dataDir, 'lifecycle.json')));
const checklist = JSON.parse(fs.readFileSync(path.join(dataDir, 'launch-checklist.json')));

const e = (v) => (v || '').replace(/'/g, "''");

const lines = [];

lines.push('-- Project 4H Dashboard — Seed Data');
lines.push('-- Auto-generated by scripts/gen-seed.js');
lines.push('');

// Ads
lines.push('-- ─── ADS ──────────────────────────────────────────────────────────────────────');
for (const ad of ads) {
  lines.push(
    `INSERT INTO ads (id, platform, campaign_group, format, primary_text, headline, cta, landing_path, utm_source, utm_medium, utm_campaign, utm_content, utm_term, status, created_at) VALUES ` +
    `('${e(ad.id)}', '${e(ad.platform)}', '${e(ad.campaignGroup)}', '${e(ad.format)}', '${e(ad.primaryText)}', '${e(ad.headline)}', '${e(ad.cta)}', '${e(ad.landingPath)}', '${e(ad.utmSource)}', '${e(ad.utmMedium)}', '${e(ad.utmCampaign)}', '${e(ad.utmContent)}', '${e(ad.utmTerm)}', '${e(ad.status)}', '${ad.createdAt}') ON CONFLICT (id) DO NOTHING;`
  );
}

// Ad status history
lines.push('');
lines.push('-- ─── AD STATUS HISTORY ────────────────────────────────────────────────────────');
for (const ad of ads) {
  if (ad.statusHistory) {
    for (const h of ad.statusHistory) {
      lines.push(
        `INSERT INTO ad_status_history (ad_id, status, note, changed_at) VALUES ('${e(ad.id)}', '${e(h.status)}', '${e(h.note)}', '${h.at}');`
      );
    }
  }
}

// Lifecycle
lines.push('');
lines.push('-- ─── LIFECYCLE MESSAGES ───────────────────────────────────────────────────────');
for (const m of lifecycle) {
  lines.push(
    `INSERT INTO lifecycle_messages (id, asset_id, channel, timing, subject, message, goal, status, updated_at) VALUES ` +
    `('${e(m.id)}', '${e(m.asset_id)}', '${e(m.channel)}', '${e(m.timing)}', '${e(m.subject || '')}', '${e(m.message)}', '${e(m.goal)}', '${e(m.status)}', '${m.updatedAt}') ON CONFLICT (id) DO NOTHING;`
  );
}

// Launch checklist
lines.push('');
lines.push('-- ─── LAUNCH CHECKLIST ─────────────────────────────────────────────────────────');
for (const item of checklist) {
  lines.push(
    `INSERT INTO launch_checklist (id, label, platform, checked) VALUES ('${e(item.id)}', '${e(item.label)}', '${e(item.platform)}', ${item.checked}) ON CONFLICT (id) DO NOTHING;`
  );
}

// Budget
lines.push('');
lines.push('-- ─── BUDGET ────────────────────────────────────────────────────────────────────');
for (const platform of ['linkedin', 'youtube', 'facebook', 'instagram']) {
  lines.push(`INSERT INTO budget (platform, allocated, spent) VALUES ('${platform}', 5000, 0) ON CONFLICT (platform) DO NOTHING;`);
}

// Campaign config
lines.push('');
lines.push('-- ─── CAMPAIGN CONFIG ───────────────────────────────────────────────────────────');
lines.push(`INSERT INTO campaign_config (id, status, total_budget) VALUES (1, 'pre-launch', 20000) ON CONFLICT (id) DO NOTHING;`);

// Initial weekly metrics
lines.push('');
lines.push('-- ─── INITIAL WEEKLY METRICS ────────────────────────────────────────────────────');
for (const platform of ['linkedin', 'youtube', 'facebook', 'instagram']) {
  lines.push(`INSERT INTO weekly_metrics (week_start, platform) VALUES ('2026-03-02', '${platform}') ON CONFLICT (week_start, platform) DO NOTHING;`);
}

// Approval queue
lines.push('');
lines.push('-- ─── APPROVAL QUEUE ────────────────────────────────────────────────────────────');
const approvalItems = [
  { id: 'LI-RT-01', type: 'retargeting_ad', title: 'LinkedIn Retargeting — Finish Setup', content: 'You already saw how Saw.City works. The only thing left is turning missed calls into booked jobs. No demo. No waiting. Start self-serve and route your first call today. | Headline: Finish setup. Start capturing jobs. | CTA: Start now', platform: 'linkedin', status: 'approved' },
  { id: 'LI-RT-02', type: 'retargeting_ad', title: 'LinkedIn Retargeting — One Step from Go-Live', content: "You're close. Most operators finish setup in minutes. Complete your setup now—no sales call required. | Headline: You're one step from go-live | CTA: Go live today", platform: 'linkedin', status: 'approved' },
  { id: 'META-RT-01', type: 'retargeting_ad', title: 'Meta Retargeting — Missed Call Recovery', content: "Missed calls don't wait. Finish your Saw.City setup and capture the jobs already trying to reach you. | Headline: Stop losing work to voicemail | CTA: Start now", platform: 'facebook', status: 'approved' },
  { id: 'META-RT-02', type: 'retargeting_ad', title: 'Meta Retargeting — Checkout Recovery', content: 'You did the hard part. Complete checkout, switch on your call flow, and run it while you are in the field. | Headline: Finish in minutes | CTA: Complete setup', platform: 'facebook', status: 'approved' },
  { id: 'YT-RT-01', type: 'retargeting_ad', title: 'YouTube Retargeting — You\'re Close (15s)', content: 'You already checked out Saw.City. Finish setup now and turn missed calls into booked jobs—without a demo call. Go live today. | CTA card: Finish setup now', platform: 'youtube', status: 'approved' },
  { id: 'YT-RT-02', type: 'retargeting_ad', title: 'YouTube Retargeting — Self-Serve Activation (30s)', content: 'If you run a small trade operation, speed matters. You already started with Saw.City—now complete setup and route your calls. No demo scheduling. | CTA card: Go live today', platform: 'youtube', status: 'approved' },
  { id: 'LPB-01', type: 'lp_block', title: 'LP Social Proof Block', content: 'Trusted by operator-led trade teams that move fast. Built for 1-10 person operator teams. Self-serve onboarding for same-day go-live.', platform: 'all', status: 'approved' },
  { id: 'LPB-02', type: 'lp_block', title: 'LP Objection Block', content: 'I don\'t have time for another system. — That\'s exactly why Saw.City exists. Setup is built to be fast, practical, and operator-friendly.', platform: 'all', status: 'approved' },
  { id: 'LPB-03', type: 'lp_block', title: 'LP Offer Stack Block', content: 'What you get when you start: Instant account + self-serve setup. Call routing + response workflow. Operator-first onboarding. Day 1/3/7 nudges.', platform: 'all', status: 'approved' },
  { id: 'LPB-04', type: 'lp_block', title: 'LP FAQ Block', content: 'Q: Do I need a demo? A: No. Q: How long setup? A: Minutes. Q: Enterprise? A: No. Q: Main outcome? A: Faster response, fewer missed opportunities.', platform: 'all', status: 'approved' },
];
for (const item of approvalItems) {
  lines.push(
    `INSERT INTO approval_queue (id, type, title, content, platform, status) VALUES ('${e(item.id)}', '${e(item.type)}', '${e(item.title)}', '${e(item.content)}', '${e(item.platform)}', '${e(item.status)}') ON CONFLICT (id) DO NOTHING;`
  );
}

const output = lines.join('\n') + '\n';
fs.writeFileSync(path.join(outDir, '002_seed.sql'), output);
console.log(`Seed SQL written — ${ads.length} ads, ${lifecycle.length} lifecycle, ${checklist.length} checklist, ${approvalItems.length} approval items`);
